package:
  name: ${{ load_from_file("pyproject.toml").project.name }}
  version: ${{ load_from_file("pyproject.toml").project.version }}

source:
  path: .
  filter:
    exclude:
      - rust/target

build:
  number: 0
  script:
    content:
      - uv pip install --no-deps --no-build-isolation -vv --system .
    env:
      CARGO_HOME: ${{ env.get("CARGO_HOME", default="") }}

requirements:
  build:
    - ${{ compiler("c") }}

    # Recent rust_osx-64 requires macosx_deployment_target_osx-64 >=11
    - rust >=1.98.0

    - ${{ stdlib("c") }}
    - if: microarch_level | int
      then: x86_64-microarch-level ==${{ microarch_level }}
  host:
    - maturin >=1.10.0
    - python 3.14.*
    - python-gil
    - uv >=0.10.2
  ignore_run_exports:
    by_name:
      - __osx

about:
  homepage: ${{ load_from_file("rust/Cargo.toml").package.homepage }}
  license: ${{ load_from_file("rust/Cargo.toml").package.license }}
  repository: ${{ load_from_file("rust/Cargo.toml").package.repository }}
