name: Update lockfiles

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 1 * *

jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0
        with:
          run-install: false
      - name: Update lockfiles
        run: |
          set -o pipefail
          pixi update --json --no-install | pixi exec pixi-diff-to-markdown >> diff.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Pixi lockfile
          title: Update Pixi lockfile
          body-path: diff.md
          branch: update-pixi
          base: main
          labels: Pixi
          delete-branch: true
          add-paths: pixi.lock
